# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '.github/workflows'
    schedule:
      interval: 'weekly'
      day: 'monday'
    groups:
      workflows:
        dependency-type: 'development'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    groups:
      dev-dependencies:
        dependency-type: 'development'
    ignore:
      - dependency-name: 'eslint'
        versions: ['>= 10']
      - dependency-name: '@eslint/js'
        versions: ['>= 10']
      - dependency-name: '@opentelemetry/auto-instrumentations-node'
        versions: ['0.70.0']
      - dependency-name: '@types/node'
        versions: ['25.3.0']
      - dependency-name: 'typescript-eslint'
        versions: ['8.56.0']
